# Path: docker-compose.yml

version: '3.8'

networks:
  astro-base-project_network:
    driver: bridge

volumes:
  web_node_modules:

services:
  web:
    container_name: astro-base-project_web
    build: web
    image: web
    networks:
      - astro-base-project_network
    volumes:
      - ./web/:/web
      - web_node_modules:/web/node_modules
    ports:
      - 3210:3210

  nginx:
    container_name: astro-base-project_nginx
    image: nginx:1.25.2-alpine-slim
    networks:
      - astro-base-project_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - 7890:7890
